server:
  http:
    addr: 0.0.0.0:8000
    timeout: 0s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 0s
data:
  database:
    dsn: "mongodb://10.181.4.10:27017"
  file:
    basePath: ./file
    filePath: .
jwt:
  secret: "hello"
